from django.conf.urls.defaults import *

urlpatterns = patterns('group.views',
    (r'^$', 'index'),
    #(r'^migrate$', 'migrate'),
    #(r'^migrate/report$', 'migrate_report'),
    #(r'^migrate/report/delete$', 'migrate_report_delete'),
    #(r'^migrate/training$', 'migrate_training'),
    #(r'^migrate/delete$', 'migrate_delete'),
    #(r'^livecenter-group-count$', 'livecenter_group_count'),
    #(r'^member-count$', 'migrate_member_count'),
    (r'^show/(?P<gid>.*)$', 'show'),
    (r'^create/(?P<lid>.*)$', 'create'),
    (r'^delete/(?P<gid>.*)$', 'delete'),
    (r'^edit/(?P<gid>.*)$', 'edit'),
    (r'^report/create/(?P<gid>.*)$', 'report_create'),
    (r'^report/edit/(?P<rid>.*)$', 'report_edit'),
    (r'^report/delete/(?P<rid>.*)$', 'report_delete'),
    (r'^training/create/(?P<gid>.*)$', 'training_create'),
    (r'^training/edit/(?P<tid>.*)$', 'training_edit'),
    (r'^training/delete/(?P<tid>.*)$', 'training_delete'),
    #(r'^map/(?P<pid>.*)$', 'map'),
)
