from django.conf.urls.defaults import *

urlpatterns = patterns('group.views',
    (r'^$', 'index'),
    (r'^migrate$', 'migrate'),
    (r'^migrate/report$', 'migrate_report'),
    (r'^migrate/report/delete$', 'migrate_report_delete'),
    (r'^migrate/training$', 'migrate_training'),
    #(r'^migrate/delete$', 'migrate_delete'),
    #(r'^livecenter-group-count$', 'livecenter_group_count'),
    (r'^show/(?P<gid>.*)$', 'show'),
    (r'^create/(?P<cid>.*)$', 'create'),
    (r'^delete/(?P<pid>.*)$', 'delete'),
    (r'^edit/(?P<gid>.*)$', 'edit'),
    (r'^add_report/(?P<pid>.*)$', 'add_report'),
    (r'^report_show/(?P<pid>.*)$', 'report_show'),
    (r'^report_delete/(?P<pid>.*)$', 'report_delete'),
    (r'^edit_report/(?P<pid>.*)$', 'edit_report'),
    (r'^add_training/(?P<pid>.*)$', 'add_training'),
    (r'^edit_training/(?P<pid>.*)$', 'edit_training'),
    #(r'^map/(?P<pid>.*)$', 'map'),
)
